SELECT * FROM DBO.DS
DECLARE @from DATETIME = '2025-03-17 09:20:00';
DECLARE @to   DATETIME = '2025-03-17 12:00:00';

SELECT 
    HOTENGV,
    MAMON,
    TENMON,
    NGAY,
    FORMAT(GIOVAO, 'HH:mm') AS GIO_BAT_DAU,
    FORMAT(GIORA, 'HH:mm') AS GIO_KET_THUC,
    MAPHONG
FROM DBO.DS
WHERE 
    NGAY = CAST(@from AS DATE) AND
    (
        (CAST(@from AS TIME) BETWEEN CAST(GIOVAO AS TIME) AND CAST(GIORA AS TIME)) OR
        (CAST(@to AS TIME)   BETWEEN CAST(GIOVAO AS TIME) AND CAST(GIORA AS TIME)) OR
        (CAST(GIOVAO AS TIME) BETWEEN CAST(@from AS TIME) AND CAST(@to AS TIME)) OR
        (CAST(GIORA AS TIME)  BETWEEN CAST(@from AS TIME) AND CAST(@to AS TIME))
    )
ORDER BY HOTENGV, GIOVAO;